x-common-volumes: &common-volumes
  - ./:/MoneyPrinterTurbo

services:
  webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "text2video-webui"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.30'
    #       memory: 5000M
    ports:
      - "8501:8501"
    command: [ "streamlit", "run", "./webui/Main.py","--browser.serverAddress=127.0.0.1","--server.enableCORS=True","--browser.gatherUsageStats=False" ]
    volumes: *common-volumes
    restart: always
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "text2video-api"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.50'
    #       memory: 5000M
    ports:
      - "8502:8502"
    command: [ "python3", "main.py" ]
    volumes: *common-volumes
    restart: always

# $ docker-compose --compatibility up -d
